-- auto-generated by todo.lua; safe to hand-edit, but keep the shape.
return {
  last_id = 13,
  tasks = {
    { id = "001", title = "Phase 0: prerequisites for wiring", status = "done", created_at = "2026-08-23T08:31:12", last_modified = "2026-08-23T09:27:10", file = "001-phase-0-prerequisites-for-wiring.md" },
    { id = "002", title = "Phase 1: construct core trio alongside legacy", status = "done", created_at = "2026-08-23T08:31:12", last_modified = "2026-08-23T09:46:27", file = "002-phase-1-construct-core-trio-alongside-legacy.md" },
    { id = "003", title = "Phase 2: inbound cutover", status = "done", created_at = "2026-08-23T08:31:12", last_modified = "2026-08-23T10:33:30", file = "003-phase-2-inbound-cutover.md" },
    { id = "004", title = "Phase 3: retire legacy path", status = "done", created_at = "2026-08-23T08:31:12", last_modified = "2026-08-23T16:08:09", file = "004-phase-3-retire-legacy-path.md" },
    { id = "005", title = "Prep: core unit tests + JsRPCMessage wire-type consolidation", status = "done", created_at = "2026-08-23T09:14:23", last_modified = "2026-08-23T09:14:23", file = "005-prep-core-unit-tests-jsrpcmessage-wire-type-consolidation.md" },
    { id = "006", title = "Event model: unified DOM-like Lua event object", status = "done", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "006-event-model-unified-dom-like-lua-event-object.md" },
    { id = "007", title = "Project structure: merge src/packages into src/modules", status = "done", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "007-project-structure-merge-srcpackages-into-srcmodules.md" },
    { id = "008", title = "Memory-safety part 1: sol3/App* lifetime guards", status = "done", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "008-memory-safety-part-1-sol3app-lifetime-guards.md" },
    { id = "009", title = "CI: ThreadSanitizer (TSAN) job", status = "done", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "009-ci-threadsanitizer-tsan-job.md" },
    { id = "010", title = "Dialog error recovery: Linux + macOS", status = "done", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "010-dialog-error-recovery-linux-macos.md" },
    { id = "011", title = "Windows dialog error recovery", status = "pending", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "011-windows-dialog-error-recovery.md" },
    { id = "012", title = "Smart-pointer migration final pass", status = "pending", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "012-smart-pointer-migration-final-pass.md" },
    { id = "013", title = "Cosmetic: stale outbox comment", status = "pending", created_at = "2026-08-28T15:09:28", last_modified = "2026-08-28T15:09:28", file = "013-cosmetic-stale-outbox-comment.md" },
  },
}
