-- Generated by Coconut Milk build pipeline.
-- Do not edit by hand.

local impl = require("commands.hello")

---@type fun(ctx: CoconutContext)
local function register(ctx)
  ctx:bind("hello", impl.hello)
  return ctx
end

return register
