#include "./command_definition.hpp"
#include "./generate.h"
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

/// Simple field extraction from a string key = "value" pattern.
/// Works for both JSON ("key": "value") and Lua (key = "value") formats.
static std::string configStringField(const std::string& text,
                                     const std::string& key) {
  // Try Lua-style: key = "value"
  {
    std::string search = key + " = \"";
    size_t pos = text.find(search);
    if (pos != std::string::npos) {
      size_t start = pos + search.size();
      size_t end = text.find('"', start);
      if (end != std::string::npos)
        return text.substr(start, end - start);
    }
  }
  // Try JSON-style: "key": "value"
  {
    std::string search = "\"" + key + "\"";
    size_t pos = text.find(search);
    if (pos == std::string::npos)
      return "";
    pos = text.find(':', pos + search.size());
    if (pos == std::string::npos)
      return "";
    pos = text.find_first_of('"', pos);
    if (pos == std::string::npos)
      return "";
    size_t end = text.find_first_of('"', pos + 1);
    if (end == std::string::npos)
      return "";
    return text.substr(pos + 1, end - pos - 1);
  }
}

static std::string deriveModulePath(const std::string& filePath) {
  std::string stem = fs::path(filePath).stem().string();
  return stem;
}

static std::string outputStem(const std::string& filePath) {
  return fs::path(filePath).stem().string();
}

/// Process a single .lua command file and generate output files.
static bool processCommandFile(const fs::path& inputPath,
                               const std::string& outDir,
                               std::vector<std::string>& allNames) {
  std::ifstream file(inputPath);
  if (!file.is_open()) {
    std::cerr << "Error: could not open " << inputPath << "\n";
    return false;
  }

  std::stringstream buffer;
  std::string line;
  while (std::getline(file, line))
    buffer << line << "\n";
  file.close();

  auto commands = coconut::generator::commentsFsm(buffer.str());
  if (commands.empty()) {
    std::cout << "  (no @command definitions in " << inputPath << ")\n";
    return true; // not an error
  }

  std::string modulePath = deriveModulePath(inputPath.string());
  std::string stem = outputStem(inputPath.string());

  fs::create_directories(outDir);

  // Collect command names for the aggregate file
  for (const auto& cmd : commands) {
    bool found = false;
    for (const auto& n : allNames)
      if (n == cmd.name) { found = true; break; }
    if (!found) allNames.push_back(cmd.name);
  }

  // .g.lua
  {
    auto luaWrap = coconut::generator::generateLuaWrapper(commands, modulePath);
    std::ofstream out(fs::path(outDir) / (stem + ".g.lua"));
    out << luaWrap;
    std::cout << "  wrote " << (fs::path(outDir) / (stem + ".g.lua")) << "\n";
  }

  // .d.ts
  {
    auto dts = coconut::generator::generateTSDefinition(commands);
    std::ofstream out(fs::path(outDir) / (stem + ".d.ts"));
    out << dts;
    std::cout << "  wrote " << (fs::path(outDir) / (stem + ".d.ts")) << "\n";
  }

  // .g.js
  {
    auto wrappers = coconut::generator::generateJSWrapper(commands);
    std::ofstream out(fs::path(outDir) / (stem + ".g.js"));
    out << wrappers;
    std::cout << "  wrote " << (fs::path(outDir) / (stem + ".g.js")) << "\n";
  }

  std::cout << "  (" << commands.size() << " command(s) from " << inputPath << ")\n";
  return true;
}

namespace coconut::generator {

int runGenerate(const std::string& cmdRoot, const std::string& outDir) {
  std::vector<std::string> allNames;

  // Resolve the command root directory
  fs::path cmdDir = cmdRoot;
  if (!fs::is_directory(cmdDir)) {
    std::cerr << "Error: command root '" << cmdRoot << "' is not a directory\n";
    return 1;
  }

  // Process each .lua file in the command root
  bool anySuccess = false;
  for (const auto& entry : fs::directory_iterator(cmdDir)) {
    if (entry.path().extension() != ".lua") continue;
    std::string name = entry.path().filename().string();
    // Skip generated files (.g.lua)
    if (name.size() > 6 && name.substr(name.size() - 6) == ".g.lua") continue;

    std::cout << "processing " << entry.path() << "\n";
    if (processCommandFile(entry.path(), outDir, allNames)) {
      anySuccess = true;
    }
  }

  // Write aggregated commands.d.ts
  if (!allNames.empty()) {
    fs::create_directories(outDir);
    std::ofstream agg(fs::path(outDir) / "commands.d.ts");
    agg << "// Auto-generated by coconut-milk generator. Do not edit.\n";
    agg << "// Aggregates all @command names from commands/*.lua.\n";
    agg << "// Included via /// <reference> in scripts/coconut.d.ts.\n";
    agg << "\n";
    agg << "type CoconutCommandName =";
    for (size_t i = 0; i < allNames.size(); ++i) {
      agg << (i == 0 ? " " : " | ") << "\"" << allNames[i] << "\"";
    }
    agg << ";\n";
    std::cout << "  wrote " << (fs::path(outDir) / "commands.d.ts") << "\n";
  }

  if (!anySuccess) {
    std::cerr << "No command files processed in " << cmdRoot << "\n";
    return 1;
  }

  std::cout << "Done. Generated " << allNames.size()
            << " unique command(s) to " << outDir << "/\n";
  return 0;
}

} // namespace coconut::generator
