-- Generated by Coconut Milk build pipeline.
-- Do not edit by hand.

local impl = require("notes")

---@type fun(ctx: CoconutContext)
local function register(ctx)
  ctx:bind("notes_list", impl.notes_list)
  ctx:bind("notes_save", impl.notes_save)
  return ctx
end

return register
