-- Generated by Coconut Milk build pipeline.
-- Do not edit by hand.

local impl = require("commands.type_pizza")

---@type fun(ctx: CoconutContext)
local function register(ctx)
  ctx:bind("noop", impl.noop)
  ctx:bind("ping", impl.ping)
  ctx:bind("greet", impl.greet)
  ctx:bind("sum", impl.sum)
  ctx:bind("login", impl.login)
  ctx:bind("search", impl.search)
  ctx:bind("transform", impl.transform)
  ctx:bind("merge", impl.merge)
  ctx:bind("evaluate", impl.evaluate)
  return ctx
end

return register
