-- Generated by Coconut Milk build pipeline.
-- Do not edit by hand.

local impl = require("calc")

---@type fun(ctx: CoconutContext)
local function register(ctx)
  ctx:bind("calc_save", impl.calc_save)
  ctx:bind("calc_load", impl.calc_load)
  ctx:bind("settings_save", impl.settings_save)
  ctx:bind("settings_load", impl.settings_load)
  return ctx
end

return register
