#!/usr/bin/env python3

import argparse


def js_to_c_header(input_filename: str, output_filename: str, symbol: str, comment: str | None = None):
    with open(input_filename, "r", encoding="utf-8") as f:
        content = f.read()

    header_comment = comment or "// --- Generated by js2c_to_header.py ---\n"

    # Convert each character to UTF-8 hex bytes.
    # Using ord(c) directly would give the full Unicode codepoint (>255 for non-ASCII)
    # which doesn't fit in unsigned char.  Encode to UTF-8 first.
    raw_bytes = content.encode("utf-8")
    hex_values = ["0x{:02x}".format(b) for b in raw_bytes]

    header_guard = symbol.upper() + "_H"

    header = "".join(
        [
            header_comment,
            f"#ifndef {header_guard}\n",
            f"#define {header_guard}\n\n",
            f"static const unsigned char {symbol}[] = {{ ",
        ]
    )

    # Pretty wrap: 10 values per line.
    for i in range(0, len(hex_values), 10):
        header += "\n  " + ", ".join(hex_values[i : i + 10]) + ","

    # Need to escape braces in format strings / f-strings.
    header += f"\n  0x00\n}};\n\n#endif // {header_guard}\n"

    with open(output_filename, "w", encoding="utf-8") as f:
        f.write(header)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True)
    ap.add_argument("--symbol", required=True)
    args = ap.parse_args()

    js_to_c_header(
        input_filename=args.input,
        output_filename=args.output,
        symbol=args.symbol,
    )


if __name__ == "__main__":
    main()
