// Auto-generated by coconut-milk generator. Do not edit.
// Aggregates all @command names from commands/*.lua.
// Included via /// <reference> in scripts/coconut.d.ts.

type CoconutCommandName = "noop" | "ping" | "greet" | "sum" | "login" | "search" | "transform" | "merge" | "evaluate" | "notes_list" | "notes_save" | "hello" | "hi" | "goodbye";
