#include "window.h"
#include "embeds/coconut_embed.h"

#include <cstddef>
#include <exception>
#include <expected>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

extern "C" {
#include <webui.h>
}

namespace coconut::window {

/// Decode the embedded coconut.js byte array into a string.
/// The embed is a null-terminated byte array generated by the build
/// pipeline from src/embeds/coconut.js.
static std::string decodeEmbed() {
  // coconut_js_embed includes the null terminator.
  size_t len = sizeof(coconut_js_embed);
  if (len > 0 && coconut_js_embed[len - 1] == 0) len -= 1;
  return std::string(
      reinterpret_cast<const char*>(coconut_js_embed), len);
}

/// Inject the Coconut runtime into an HTML page.
/// Inserts a <script> block before </body> (or appends it if no
/// </body> is found).  The script provides the frontend API:
/// coconut.on(), coconut.call(), coconut.emit(), coconut.ready().
///
/// WebUI requires HTML content to start with <html>, <!DOCTYPE>,
/// or <!doctype> — fragments like "<h1>Hello</h1>" are not recognised
/// as HTML and get treated as a file path.  We wrap bare fragments
/// in a minimal HTML5 document so WebUI always serves them as HTML.
static std::string injectRuntime(const std::string& html) {
  std::string js = decodeEmbed();
  std::string script =
      "<script>\n" + js + "\n</script>";

  // Check if the input already has a structural tag.
  bool hasHtml = (html.find("<html") != std::string::npos ||
                  html.find("<!DOCTYPE") != std::string::npos ||
                  html.find("<!doctype") != std::string::npos);

  if (hasHtml) {
    // Full document — inject before </body> or </html>.
    auto pos = html.rfind("</body>");
    if (pos != std::string::npos) {
      return html.substr(0, pos) + script + "\n" + html.substr(pos);
    }
    pos = html.rfind("</html>");
    if (pos != std::string::npos) {
      return html.substr(0, pos) + script + "\n" + html.substr(pos);
    }
    // Structural tag but no close — append.
    return html + "\n" + script;
  }

  // Bare fragment — wrap in a minimal HTML5 document with the script.
  return
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head><meta charset=\"UTF-8\"></head>\n"
    "<body>\n" +
    html + "\n" +
    script + "\n" +
    "</body>\n"
    "</html>";
}

std::expected<Window *, Error> createWindow(Config *config, size_t window_id) {
  if (window_id == 0) {
    return std::unexpected(Error{.code = ErrorCode::WebUiError, .message = "Invalid WebUI window id"});
  }

  // Keep timeout behavior here to centralize window settings.
  webui_set_timeout(20);

  return new Window{.configs = config, .views = {}, .window_id = window_id};
}

void destroyWindow(Window *window) {
  if (window == nullptr) {
    return;
  }

  // Defensive: webui_destroy may fail on invalid ID, guard it.
  if (window->window_id > 0) {
    webui_destroy(window->window_id);
  }

  // Free any heap-allocated views to prevent memory leaks.
  for (auto& [name, vp] : window->views) {
    (void)name;
    delete vp;
  }
  window->views.clear();

  delete window;
}

void showWindow(Window *window) {
  if (window == nullptr) {
    return;
  }

  // Guard against null config — use hardcoded defaults as fallback.
  int w = 1280;
  int h = 640;
  if (window->configs != nullptr) {
    w = window->configs->window_width;
    h = window->configs->window_height;
  }
  webui_set_size(window->window_id, w, h);

  const std::string& view_name = window->current_view;
  if (view_name.empty()) {
    webui_show_browser(window->window_id,
               "<!DOCTYPE html><html lang=\"en\"><body><h1>default View</h1></body></html>",webui_browser::AnyBrowser);
    return;
  }

  // Use find() — never at() which throws on missing key.
  const auto it = window->views.find(view_name);
  if (it == window->views.end() || it->second == nullptr) {
    webui_show_browser(window->window_id,
               "<!DOCTYPE html><html lang=\"en\"><body><h1>View not found</h1></body></html>",webui_browser::AnyBrowser);
    return;
  }

  webui_show_browser(window->window_id, it->second->html.c_str(),webui_browser::AnyBrowser);
}

void showView(Window *window, std::string name) {
  if (window == nullptr) {
    return;
  }

  // Defensive: only switch if the view exists; otherwise stay on current.
  if (window->views.count(name)) {
    window->current_view = std::move(name);
    showWindow(window);
  }
}

void addView(Window *window, std::string name, View *view) {
  if (window != nullptr && view != nullptr) {
    window->views[name] = view;
  }
}

std::expected<View, Error> createView(std::string pathOrCode, ViewKind kind,
                                      std::optional<ViewConfig> configs) {
  View view{.kind = kind};

  switch (kind) {
  case VIEW_KIND_FILE: {
    try {
      std::stringstream text_content;
      std::ifstream file(pathOrCode);
      if (!file.is_open()) {
        return std::unexpected(
            Error{.code = ErrorCode::MissingFile,
                  .message = "could not open file: " + pathOrCode});
      }
      std::string line;
      while (std::getline(file, line)) {
        text_content << line << '\n';
      }
      view.html = text_content.str();
    } catch (const std::exception &e) {
      return std::unexpected(
          Error{.code = ErrorCode::MissingFile,
                .message = std::string("file read error: ") + e.what()});
    }
    break;
  }
  case VIEW_KIND_HTML:
    view.html = pathOrCode;
    break;
  case VIEW_KIND_URL:
    return std::unexpected(Error{.code = ErrorCode::NotImplementedYet,
                                 .message = "URL views not yet implemented"});
  }

  // Inject the Coconut frontend runtime (coconut.on, .call, .emit, etc.)
  // into every local view so the frontend can communicate with Lua.
  if (kind == VIEW_KIND_FILE || kind == VIEW_KIND_HTML) {
    view.html = injectRuntime(view.html);
  }

  return view;
}

} // namespace coconut::window
